sudo: required
services:
  - docker

before_install:
  - docker build -f ./client/Dockerfile.dev -t nkdocker/react-test ./client

script:
  - docker run -e CI=true nkdocker/react-test npm test
  
after_success:
  - docker build -t nkdocker/multi-client ./client
  - docker build -t nkdocker/multi-server ./server
  - docker build -t nkdocker/multi-nginx ./nginx
  - docker build -t nkdocker/multi-worker ./worker
  # Take those images and push them to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push nkdocker/multi-client
  - docker push nkdocker/multi-server
  - docker push nkdocker/multi-nginx
  - docker push nkdocker/multi-worker

deploy:
  provider: elasticbeanstalk
  region: eu-west-3
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-west-3-382120047160
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
